/*
 * AdminUI.java
 *
 * Created on February 10, 2008, 12:35 PM
 */

package persistence.client;

import bsh.Interpreter;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.event.TreeExpansionEvent;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.event.TreeWillExpandListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.ExpandVetoException;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreeSelectionModel;
import persistence.Array;
import persistence.Connection;
import persistence.Connections;
import persistence.PersistentClass;
import persistence.PersistentObject;

/**
 *
 * @author  raphael
 */
public class AdminUI extends javax.swing.JFrame {
	Connection conn;
	DefaultTreeModel model=new DefaultTreeModel(ObjectTreeNode.node(null,"system"));
	Interpreter interpreter;

	/** Creates new form AdminUI */
	public AdminUI() {
		initComponents();
		jDialog1.pack();
		jDialog2.pack();
		jTree1.setModel(model);
		jTree1.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
		jTree1.addTreeSelectionListener(new TreeSelectionListener() {
			public void valueChanged(TreeSelectionEvent e) {
				ObjectTreeNode node = (ObjectTreeNode)jTree1.getLastSelectedPathComponent();
				Object object = node==null?null:node.object;
				int n = jSplitPane1.getDividerLocation();
				if(object instanceof PersistentObject) {
					jTable1.setModel(ObjectTableModel.model(object));
					jSplitPane1.setRightComponent(jScrollPane3);
				} else {
					jTextArea1.setText(String.valueOf(object));
					jSplitPane1.setRightComponent(jScrollPane2);
				}
				jSplitPane1.setDividerLocation(n);
			}
		});
		jTree1.addTreeWillExpandListener(new TreeWillExpandListener() {
			public void treeWillCollapse(TreeExpansionEvent event) throws ExpandVetoException {}

			public void treeWillExpand(TreeExpansionEvent event) throws ExpandVetoException {
				model.reload((TreeNode)event.getPath().getLastPathComponent());
			}
		});
		interpreter = new Interpreter( jConsole1 );
		new Thread( interpreter ).start(); // start a thread to call the run() method
	}

	void open() {
		try {
			boolean admin=jCheckBox1.isSelected();
			String location=jTextField1.getText();
			conn=admin?Connections.getAdminConnection(location):Connections.getConnection(location);
			model.setRoot(ObjectTreeNode.node(conn.system(),"system"));
			model.reload();
			interpreter.set("conn",conn);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	void close() {
		try {
			interpreter.set("conn",null);
			model.setRoot(ObjectTreeNode.node(null,"system"));
			model.reload();
			conn.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	void setDialogLocation(Component dialog) {
		Point location=this.getLocation();
		Dimension size=this.getSize();
		Dimension s=dialog.getSize();
		location.translate((size.width-s.width)>>1,(size.height-s.height)>>1);
		dialog.setLocation(location);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane3 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jDialog1 = new javax.swing.JDialog();
                jLabel1 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jCheckBox1 = new javax.swing.JCheckBox();
                jDialog2 = new javax.swing.JDialog();
                jLabel2 = new javax.swing.JLabel();
                jButton3 = new javax.swing.JButton();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jSplitPane1 = new javax.swing.JSplitPane();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTree1 = new javax.swing.JTree();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jConsole1 = new bsh.util.JConsole();
                menuBar = new javax.swing.JMenuBar();
                fileMenu = new javax.swing.JMenu();
                openMenuItem = new javax.swing.JMenuItem();
                closeMenuItem = new javax.swing.JMenuItem();
                exitMenuItem = new javax.swing.JMenuItem();
                helpMenu = new javax.swing.JMenu();
                aboutMenuItem = new javax.swing.JMenuItem();

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2"
                        }
                ));
                jScrollPane3.setViewportView(jTable1);

                jDialog1.setTitle("Open connection");

                jLabel1.setText("Location :");

                jTextField1.setText("//localhost/store");

                jButton1.setText("Ok");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setText("Cancel");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jCheckBox1.setSelected(true);
                jCheckBox1.setText("Admin");

                org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
                jDialog1.getContentPane().setLayout(jDialog1Layout);
                jDialog1Layout.setHorizontalGroup(
                        jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jDialog1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jDialog1Layout.createSequentialGroup()
                                                .add(jLabel1)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialog1Layout.createSequentialGroup()
                                                .add(jButton1)
                                                .add(18, 18, 18)
                                                .add(jButton2))
                                        .add(jCheckBox1))
                                .addContainerGap())
                );
                jDialog1Layout.setVerticalGroup(
                        jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jDialog1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel1)
                                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jCheckBox1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jButton2)
                                        .add(jButton1))
                                .addContainerGap())
                );

                jLabel2.setText("<html>databeans : a new, fully object oriented persistence framework for java<br/>Copyright (C) 2007-2008 Databeans</html>");

                jButton3.setText("Ok");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                org.jdesktop.layout.GroupLayout jDialog2Layout = new org.jdesktop.layout.GroupLayout(jDialog2.getContentPane());
                jDialog2.getContentPane().setLayout(jDialog2Layout);
                jDialog2Layout.setHorizontalGroup(
                        jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jDialog2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel2)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialog2Layout.createSequentialGroup()
                                .addContainerGap(433, Short.MAX_VALUE)
                                .add(jButton3)
                                .addContainerGap())
                );
                jDialog2Layout.setVerticalGroup(
                        jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jDialog2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel2)
                                .add(18, 18, 18)
                                .add(jButton3)
                                .addContainerGap(29, Short.MAX_VALUE))
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jScrollPane1.setViewportView(jTree1);

                jSplitPane1.setLeftComponent(jScrollPane1);

                jTextArea1.setColumns(20);
                jTextArea1.setEditable(false);
                jTextArea1.setLineWrap(true);
                jTextArea1.setRows(5);
                jScrollPane2.setViewportView(jTextArea1);

                jSplitPane1.setRightComponent(jScrollPane2);

                jTabbedPane1.addTab("system", jSplitPane1);
                jTabbedPane1.addTab("console", jConsole1);

                fileMenu.setText("Connection");

                openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
                openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/development/Server16.gif"))); // NOI18N
                openMenuItem.setText("Open");
                openMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                openMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(openMenuItem);

                closeMenuItem.setText("Close");
                closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                closeMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(closeMenuItem);

                exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
                exitMenuItem.setText("Exit");
                exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exitMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(exitMenuItem);

                menuBar.add(fileMenu);

                helpMenu.setText("Help");

                aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/About16.gif"))); // NOI18N
                aboutMenuItem.setText("About");
                aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                aboutMenuItemActionPerformed(evt);
                        }
                });
                helpMenu.add(aboutMenuItem);

                menuBar.add(helpMenu);

                setJMenuBar(menuBar);

                org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}//GEN-LAST:event_exitMenuItemActionPerformed

	private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
		setDialogLocation(jDialog1);
		jDialog1.setVisible(true);
	}//GEN-LAST:event_openMenuItemActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		jDialog1.setVisible(false);
		open();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		jDialog1.setVisible(false);
	}//GEN-LAST:event_jButton2ActionPerformed

	private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
		setDialogLocation(jDialog2);
		jDialog2.setVisible(true);
	}//GEN-LAST:event_aboutMenuItemActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		jDialog2.setVisible(false);
	}//GEN-LAST:event_jButton3ActionPerformed

	private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
		close();
	}//GEN-LAST:event_closeMenuItemActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminUI().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem aboutMenuItem;
        private javax.swing.JMenuItem closeMenuItem;
        private javax.swing.JMenuItem exitMenuItem;
        private javax.swing.JMenu fileMenu;
        private javax.swing.JMenu helpMenu;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JCheckBox jCheckBox1;
        private bsh.util.JConsole jConsole1;
        private javax.swing.JDialog jDialog1;
        private javax.swing.JDialog jDialog2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JSplitPane jSplitPane1;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTree jTree1;
        private javax.swing.JMenuBar menuBar;
        private javax.swing.JMenuItem openMenuItem;
        // End of variables declaration//GEN-END:variables
}

class ObjectTreeNode implements TreeNode {
	Object object;
	String name;
	TreeNode parent;
	String fields[];

	public ObjectTreeNode(Object object, String name, TreeNode parent) {
		this.object=object;
		this.name=name;
		this.parent=parent;
		if(object instanceof PersistentObject) {
			PersistentObject obj=(PersistentObject)object;
			PersistentClass clazz=obj.persistentClass();
			String str=clazz.getFields();
			fields=str.length()==0?new String[0]:str.split(";");
		} else fields=new String[0];
	}

	public Enumeration children() {
		return new Enumeration() {
			int index;

			public boolean hasMoreElements() {
				return index<fields.length;
			}

			public Object nextElement() {
				return get(index++);
			}
		};
	}

	Object get(int n) {
		String f=fields[n];
		try {
			return object.getClass().getMethod((f.substring(0, 1).equals("Z")?"is":"get")+f.substring(2, 3).toUpperCase()+f.substring(3), new Class[] {}).invoke(object, new Object[] {});
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

	public boolean getAllowsChildren() {
		return false;
	}

	public TreeNode getChildAt(int childIndex) {
		return ObjectTreeNode.node(get(childIndex),fields[childIndex].substring(2),this);
	}

	public int getChildCount() {
		return fields.length;
	}

	public int getIndex(TreeNode node) {
		for(int i=0;i<fields.length;i++) if(fields[i].substring(2).equals(((ObjectTreeNode)node).name)) return i;
		return -1;
	}

	public TreeNode getParent() {
		return parent;
	}

	public boolean isLeaf() {
		return fields.length==0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final ObjectTreeNode other = (ObjectTreeNode) obj;
		if (this.name != other.name && (this.name == null || !this.name.equals(other.name))) {
			return false;
		}
		return true;
	}

	public int hashCode() {
		int hash = 7;
		hash = 53 * hash + (this.name != null ? this.name.hashCode() : 0);
		return hash;
	}

	public String toString() {
		return name;
	}

	static ObjectTreeNode node(Object object, String name) {
		return node(object,name,null);
	}

	static ObjectTreeNode node(Object object, String name, TreeNode parent) {
		if(object instanceof Array) return new ArrayTreeNode((Array)object,name,parent);
		else if(object instanceof Map) return new MapTreeNode((Map)object,name,parent);
		else if(object instanceof List) return new ListTreeNode((List)object,name,parent);
		else if(object instanceof Collection) return node(new ArrayList((Collection)object),name,parent);
		else return new ObjectTreeNode(object,name,parent);
	}
}

class ArrayTreeNode extends ObjectTreeNode {
	Array array;

	public ArrayTreeNode(Array array, String name, TreeNode parent) {
		super(array,name,parent);
		this.array=(Array)object;
	}

	public Enumeration children() {
		return new Enumeration() {
			int index;

			public boolean hasMoreElements() {
				return index<array.length();
			}

			public Object nextElement() {
				return get(index++);
			}
		};
	}

	Object get(int n) {
		return array.get(n);
	}

	public TreeNode getChildAt(int childIndex) {
		return ObjectTreeNode.node(get(childIndex),String.valueOf(childIndex),this);
	}

	public int getChildCount() {
		return array.length();
	}

	public int getIndex(TreeNode node) {
		return Integer.valueOf(((ObjectTreeNode)node).name).intValue();
	}

	public boolean isLeaf() {
		return array.length()==0;
	}
}

class ListTreeNode extends ObjectTreeNode {
	List list;

	public ListTreeNode(List list, String name, TreeNode parent) {
		super(list,name,parent);
		this.list=(List)object;
	}

	public Enumeration children() {
		return new Enumeration() {
			Iterator iterator=list.iterator();

			public boolean hasMoreElements() {
				return iterator.hasNext();
			}

			public Object nextElement() {
				return iterator.next();
			}
		};
	}

	Object get(int n) {
		return list.get(n);
	}

	public TreeNode getChildAt(int childIndex) {
		return ObjectTreeNode.node(get(childIndex),String.valueOf(childIndex),this);
	}

	public int getChildCount() {
		return list.size();
	}

	public int getIndex(TreeNode node) {
		return Integer.valueOf(((ObjectTreeNode)node).name).intValue();
	}

	public boolean isLeaf() {
		return list.isEmpty();
	}
}

class MapTreeNode extends ObjectTreeNode {
	Map map;
	Object keys[];

	public MapTreeNode(Map map, String name, TreeNode parent) {
		super(map,name,parent);
		this.map=(Map)object;
		keys=map.keySet().toArray();
	}

	public Enumeration children() {
		return new Enumeration() {
			Iterator iterator=map.values().iterator();

			public boolean hasMoreElements() {
				return iterator.hasNext();
			}

			public Object nextElement() {
				return iterator.next();
			}
		};
	}

	Object get(int n) {
		return map.get(keys[n]);
	}

	public boolean getAllowsChildren() {
		return false;
	}

	public TreeNode getChildAt(int childIndex) {
		return ObjectTreeNode.node(get(childIndex),keys[childIndex].toString(),this);
	}

	public int getChildCount() {
		return keys.length;
	}

	public int getIndex(TreeNode node) {
		for(int i=0;i<keys.length;i++) if(keys[i].toString().equals(((ObjectTreeNode)node).name)) return i;
		return -1;
	}

	public boolean isLeaf() {
		return keys.length==0;
	}
}

class ObjectTableModel extends AbstractTableModel {
	Object object;
	String fields[];

	public ObjectTableModel(Object object) {
		this.object=object;
		if(object instanceof PersistentObject) {
			PersistentObject obj=(PersistentObject)object;
			PersistentClass clazz=obj.persistentClass();
			String str=clazz.getFields();
			fields=str.length()==0?new String[0]:str.split(";");
		} else fields=new String[0];
	}

	public int getColumnCount() {
		return 2;
	}

	public int getRowCount() {
		return fields.length;
	}

	public String getColumnName(int column) {
		switch(column) {
			case 0:
				return "field";
			case 1:
				return "value";
			default:
				return null;
		}
	}

	public Object getValueAt(int rowIndex, int columnIndex) {
		switch(columnIndex) {
			case 0:
				return fields[rowIndex].substring(2);
			case 1:
				return get(rowIndex);
			default:
				return null;
		}
	}

	Object get(int n) {
		String f=fields[n];
		try {
			return object.getClass().getMethod((f.substring(0, 1).equals("Z")?"is":"get")+f.substring(2, 3).toUpperCase()+f.substring(3), new Class[] {}).invoke(object, new Object[] {});
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

	static ObjectTableModel model(Object object) {
		if(object instanceof Array) return new ArrayTableModel((Array)object);
		else if(object instanceof Map) return new MapTableModel((Map)object);
		else if(object instanceof List) return new ListTableModel((List)object);
		else if(object instanceof Collection) return model(new ArrayList((Collection)object));
		else return new ObjectTableModel(object);
	}
}

class ArrayTableModel extends ObjectTableModel {
	Array array;

	public ArrayTableModel(Array array) {
		super(array);
		this.array=(Array)object;
	}

	public int getRowCount() {
		return array.length();
	}

	public String getColumnName(int column) {
		switch(column) {
			case 0:
				return "index";
			case 1:
				return "value";
			default:
				return null;
		}
	}

	public Object getValueAt(int rowIndex, int columnIndex) {
		switch(columnIndex) {
			case 0:
				return new Integer(rowIndex);
			case 1:
				return get(rowIndex);
			default:
				return null;
		}
	}

	Object get(int n) {
		return array.get(n);
	}
}

class ListTableModel extends ObjectTableModel {
	List list;

	public ListTableModel(List list) {
		super(list);
		this.list=(List)object;
	}

	public int getRowCount() {
		return list.size();
	}

	public String getColumnName(int column) {
		switch(column) {
			case 0:
				return "index";
			case 1:
				return "value";
			default:
				return null;
		}
	}

	public Object getValueAt(int rowIndex, int columnIndex) {
		switch(columnIndex) {
			case 0:
				return new Integer(rowIndex);
			case 1:
				return get(rowIndex);
			default:
				return null;
		}
	}

	Object get(int n) {
		return list.get(n);
	}
}

class MapTableModel extends ObjectTableModel {
	Map map;
	Object keys[];

	public MapTableModel(Map map) {
		super(map);
		this.map=(Map)object;
		keys=map.keySet().toArray();
	}

	public int getRowCount() {
		return keys.length;
	}

	public String getColumnName(int column) {
		switch(column) {
			case 0:
				return "key";
			case 1:
				return "value";
			default:
				return null;
		}
	}

	public Object getValueAt(int rowIndex, int columnIndex) {
		switch(columnIndex) {
			case 0:
				return keys[rowIndex];
			case 1:
				return get(rowIndex);
			default:
				return null;
		}
	}

	Object get(int n) {
		return map.get(keys[n]);
	}
}
